# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Calculadora.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(314, 411)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.boton_del = QtWidgets.QPushButton(self.centralwidget)
        self.boton_del.setGeometry(QtCore.QRect(10, 80, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.boton_del.setFont(font)
        self.boton_del.setObjectName("boton_del")
        self.boton_ce = QtWidgets.QPushButton(self.centralwidget)
        self.boton_ce.setGeometry(QtCore.QRect(70, 80, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.boton_ce.setFont(font)
        self.boton_ce.setObjectName("boton_ce")
        self.boton_c = QtWidgets.QPushButton(self.centralwidget)
        self.boton_c.setGeometry(QtCore.QRect(130, 80, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.boton_c.setFont(font)
        self.boton_c.setObjectName("boton_c")
        self.boton_mas_menos = QtWidgets.QPushButton(self.centralwidget)
        self.boton_mas_menos.setGeometry(QtCore.QRect(190, 80, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.boton_mas_menos.setFont(font)
        self.boton_mas_menos.setObjectName("boton_mas_menos")
        self.boton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.boton_7.setGeometry(QtCore.QRect(10, 140, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.boton_7.setFont(font)
        self.boton_7.setObjectName("boton_7")
        self.boton_1_x = QtWidgets.QPushButton(self.centralwidget)
        self.boton_1_x.setGeometry(QtCore.QRect(250, 200, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.boton_1_x.setFont(font)
        self.boton_1_x.setObjectName("boton_1_x")
        self.boton_raiz = QtWidgets.QPushButton(self.centralwidget)
        self.boton_raiz.setGeometry(QtCore.QRect(250, 80, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.boton_raiz.setFont(font)
        self.boton_raiz.setObjectName("boton_raiz")
        self.boton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.boton_5.setGeometry(QtCore.QRect(70, 200, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.boton_5.setFont(font)
        self.boton_5.setObjectName("boton_5")
        self.boton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.boton_8.setGeometry(QtCore.QRect(70, 140, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.boton_8.setFont(font)
        self.boton_8.setObjectName("boton_8")
        self.boton_9 = QtWidgets.QPushButton(self.centralwidget)
        self.boton_9.setGeometry(QtCore.QRect(130, 140, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.boton_9.setFont(font)
        self.boton_9.setObjectName("boton_9")
        self.boton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.boton_2.setGeometry(QtCore.QRect(70, 260, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.boton_2.setFont(font)
        self.boton_2.setObjectName("boton_2")
        self.boton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.boton_3.setGeometry(QtCore.QRect(130, 260, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.boton_3.setFont(font)
        self.boton_3.setObjectName("boton_3")
        self.boton_menos = QtWidgets.QPushButton(self.centralwidget)
        self.boton_menos.setGeometry(QtCore.QRect(190, 260, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.boton_menos.setFont(font)
        self.boton_menos.setObjectName("boton_menos")
        self.boton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.boton_4.setGeometry(QtCore.QRect(10, 200, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.boton_4.setFont(font)
        self.boton_4.setObjectName("boton_4")
        self.boton_div = QtWidgets.QPushButton(self.centralwidget)
        self.boton_div.setGeometry(QtCore.QRect(190, 140, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.boton_div.setFont(font)
        self.boton_div.setObjectName("boton_div")
        self.boton_division = QtWidgets.QPushButton(self.centralwidget)
        self.boton_division.setGeometry(QtCore.QRect(250, 140, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.boton_division.setFont(font)
        self.boton_division.setObjectName("boton_division")
        self.boton_1 = QtWidgets.QPushButton(self.centralwidget)
        self.boton_1.setGeometry(QtCore.QRect(10, 260, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.boton_1.setFont(font)
        self.boton_1.setObjectName("boton_1")
        self.boton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.boton_6.setGeometry(QtCore.QRect(130, 200, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.boton_6.setFont(font)
        self.boton_6.setObjectName("boton_6")
        self.boton_multi = QtWidgets.QPushButton(self.centralwidget)
        self.boton_multi.setGeometry(QtCore.QRect(190, 200, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.boton_multi.setFont(font)
        self.boton_multi.setObjectName("boton_multi")
        self.boton_igual = QtWidgets.QPushButton(self.centralwidget)
        self.boton_igual.setGeometry(QtCore.QRect(250, 260, 51, 111))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.boton_igual.setFont(font)
        self.boton_igual.setObjectName("boton_igual")
        self.boton_0 = QtWidgets.QPushButton(self.centralwidget)
        self.boton_0.setGeometry(QtCore.QRect(10, 320, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.boton_0.setFont(font)
        self.boton_0.setObjectName("boton_0")
        self.boton_coma = QtWidgets.QPushButton(self.centralwidget)
        self.boton_coma.setGeometry(QtCore.QRect(130, 320, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.boton_coma.setFont(font)
        self.boton_coma.setObjectName("boton_coma")
        self.boton_mas = QtWidgets.QPushButton(self.centralwidget)
        self.boton_mas.setGeometry(QtCore.QRect(190, 320, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.boton_mas.setFont(font)
        self.boton_mas.setObjectName("boton_mas")
        self.mostrar_operaciones = QtWidgets.QLineEdit(self.centralwidget)
        self.mostrar_operaciones.setGeometry(QtCore.QRect(10, 10, 291, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.mostrar_operaciones.setFont(font)
        self.mostrar_operaciones.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.mostrar_operaciones.setObjectName("mostrar_operaciones")
        self.mostrar_resultado = QtWidgets.QLineEdit(self.centralwidget)
        self.mostrar_resultado.setGeometry(QtCore.QRect(10, 30, 291, 41))
        font = QtGui.QFont()
        font.setPointSize(27)
        self.mostrar_resultado.setFont(font)
        self.mostrar_resultado.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.mostrar_resultado.setObjectName("mostrar_resultado")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 314, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.boton_del.setText(_translate("MainWindow", "<"))
        self.boton_ce.setText(_translate("MainWindow", "CE"))
        self.boton_c.setText(_translate("MainWindow", "C"))
        self.boton_mas_menos.setText(_translate("MainWindow", "±"))
        self.boton_7.setText(_translate("MainWindow", "7"))
        self.boton_1_x.setText(_translate("MainWindow", "1/x"))
        self.boton_raiz.setText(_translate("MainWindow", "√"))
        self.boton_5.setText(_translate("MainWindow", "5"))
        self.boton_8.setText(_translate("MainWindow", "8"))
        self.boton_9.setText(_translate("MainWindow", "9"))
        self.boton_2.setText(_translate("MainWindow", "2"))
        self.boton_3.setText(_translate("MainWindow", "3"))
        self.boton_menos.setText(_translate("MainWindow", "-"))
        self.boton_4.setText(_translate("MainWindow", "4"))
        self.boton_div.setText(_translate("MainWindow", "/"))
        self.boton_division.setText(_translate("MainWindow", "%"))
        self.boton_1.setText(_translate("MainWindow", "1"))
        self.boton_6.setText(_translate("MainWindow", "6"))
        self.boton_multi.setText(_translate("MainWindow", "*"))
        self.boton_igual.setText(_translate("MainWindow", "="))
        self.boton_0.setText(_translate("MainWindow", "0"))
        self.boton_coma.setText(_translate("MainWindow", ","))
        self.boton_mas.setText(_translate("MainWindow", "+"))
        self.mostrar_operaciones.setText(_translate("MainWindow", "0"))
        self.mostrar_resultado.setText(_translate("MainWindow", "0"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

